- name: Set timezone
  ansible.builtin.timezone:
    name: Europe/Moscow

- name: Install zabbix repo
  apt:
    deb: https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu20.04_all.deb

- name: Install zabbix-agent
  package:
    name: zabbix-agent2
    state: latest

- name: Copy config zabbix-agent
  ansible.builtin.copy:
    src: zabbix_agent2.conf
    dest: /etc/zabbix/zabbix_agent2.conf
  register: reconf

- name: Restart zabbix-agent
  ansible.builtin.service:
    name: zabbix-agent2
    enabled: yes
    state: restarted
  when: reconf.changed
